
version: '0.1'

services:

  database:
    image: mysql
    ports:
      - '1001:3306'
    expose:
      - '1001'
    environment:
      MYSQL_DATABASE: 'db'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'dsa3101'
      MYSQL_ROOT_PASSWORD: 'dsa3101'