version: "1"

services:
  web:
    build: 
      context: .
      dockerfile: flask_dockerfile
    ports:
      - "9001:5000"
  db:
    image: "imxuanjun/solace_trust"
    platform: "linux/amd64"
  user:
    build:
      context: .
      dockerfile: user_dockerfile
    stdin_open: true
    tty: true
    volumes:
      - type: bind
        source: ./data
        target: /data
    
